import os
params = {
  "model_type": "conv_lca",
  "model_name": "conv_lca_vh",
  "version": "4.0",
  "num_images": 250,
  "image_edge_size": 256,
  "vectorize_data": False,
  "center_data": True,
  "norm_data": False,
  "whiten_data": True,
  "contrast_normalize": False,
  "extract_patches": False,
  "batch_size": 1,
  "stride_y": 8,
  "stride_x": 8,
  "patch_size_y": 16,
  "patch_size_x": 16,
  "num_neurons": 512, # pixel-overcompleteness is num_neurons/(stride_y * stride_x)
  "num_steps": 100,
  "dt": 0.001,
  "tau": 0.03,
  "rectify_a": True,
  "norm_weights": True,
  "thresh_type": "soft",
  "optimizer": "annealed_sgd",#"adadelta",
  "cp_int": 10000,
  "max_cp_to_keep": 1,
  "cp_load": False,
  "log_int": 10,
  "log_to_file": True,
  "gen_plot_int": 1000,
  "save_plots": True,
  "eps": 1e-12,
  "device": "/gpu:0",
  "rand_seed": 1234567890,
  "out_dir": os.path.expanduser("~")+"/Work/Projects/",
  "data_dir": os.path.expanduser("~")+"/Work/Datasets/"}

schedule = [
  {"weights": ["phi"],
  "sparse_mult": 0.06,
  "weight_lr": [0.04],
  "decay_steps": [int(5e4*0.8)],
  "decay_rate": [0.8],
  "staircase": [True],
  "num_batches": int(5e4)}]
