import os
params = {
  "model_type": "dsc",
  "model_name": "test",
  "version": "0.0",
  "optimizer": "annealed_sgd",
  "rectify_u": True,
  "rectify_v": True,
  "norm_images": False,
  "whiten_images": True,
  "norm_weights": False,
  "epoch_size": 1000000,
  "patch_edge_size": 20,
  "overlapping_patches": True,
  "patch_variance_threshold": 1e-6,
  "batch_size": 100,
  "num_u": 841,
  "num_v": 20,
  "num_steps": 20,
  "cp_int": 50000,
  "max_cp_to_keep": 5,
  "cp_load": False,
  "cp_load_name": "pretrain",
  "cp_load_val": 150000,
  "cp_load_ver": "0.0",
  "cp_load_var": ["a"],
  "log_int": 100,
  "log_to_file": True,
  "gen_plot_int": 100,
  "save_plots": True,
  "eps": 1e-12,
  "device": "/cpu:0",
  "rand_seed": 1234567890,
  "out_dir": os.path.expanduser("~")+"/Work/Projects/",
  "data_dir": os.path.expanduser("~")+"/Work/Datasets/"}

schedule = [
  {"weights": ["a"],
  "recon_mult": 1.0,
  "sparse_mult": 0.7,
  "a_decay_mult": 0.9,
  "b_decay_mult": 0.0,
  "u_step_size": 0.01,
  "v_step_size":0.0,
  "weight_lr": [0.1],
  "decay_steps": [25000],
  "decay_rate": [0.9],
  "staircase": [True],
  "num_batches": 50000}]#,

  #{"weights": ["a", "b"],
  #"recon_mult": 1.0,
  #"sparse_mult": 0.2,
  #"a_decay_mult": 0.5,
  #"b_decay_mult": 0.5,
  #"u_step_size": 0.01,
  #"v_step_size": 0.001,
  #"weight_lr": [0.1, 0.001],
  #"decay_steps": [15000]*2,
  #"decay_rate": [0.8]*2,
  #"staircase": [True]*2,
  #"num_batches": 15000}]
