import os
import numpy as np
params = {
  "model_type": "gdn_autoencoder",
  "model_name": "gdn_autoencoder",
  "version": "1.0",
  "num_images": 150,
  "vectorize_data": True,
  "norm_data": False,
  "center_data": False,
  "standardize_data": True,
  "contrast_normalize": False,
  "whiten_data": True,
  "whiten_method": "FT",
  "extract_patches": True,
  "num_patches": 1e6,
  "patch_edge_size": 9,
  "overlapping_patches": True,
  "randomize_patches": True,
  "patch_variance_threshold": 1e-6,
  "batch_size": 300,
  "num_neurons": 81,
  "mle_step_size": 0.01,
  "num_mle_steps": 15,
  "num_triangles": 20,
  "sigmoid_beta": 2.0,
  "optimizer": "adam",#"annealed_sgd",
  "cp_int": 10000,
  "max_cp_to_keep": 1,
  "cp_load": True,
  "cp_load_name": "gdn_autoencoder",
  "cp_load_step": 1e4,
  "cp_load_ver": "0.0",
  "cp_load_var": ["w_enc", "b_enc", "w_dec", "b_dec", "gdn_w", "gdn_b", "igdn_w", "igdn_b"],
  "log_int": 10,
  "log_to_file": True,
  "gen_plot_int": 10000,
  "save_plots": True,
  "eps": 1e-12,
  "device": "/gpu:0",
  "rand_seed": 1234567890,
  "out_dir": os.path.expanduser("~")+"/Work/Projects/",
  "data_dir": os.path.expanduser("~")+"/Work/Datasets/"}

schedule = [
  {"weights": ["w_enc", "b_enc", "w_dec", "b_dec", "gdn_w", "gdn_b", "igdn_w", "igdn_b"],
  "ent_mult": 0.10,
  "triangle_centers": np.linspace(-1.0, 1.0, params["num_triangles"]),
  #"weight_lr": [0.08,]*4+[0.001,]*4,
  "weight_lr": [0.005,]*4+[0.01,]*4,
  "decay_steps": [int(1e5*0.8),]*8,
  "decay_rate": [0.5,]*8,
  "staircase": [True,]*8,
  "num_batches": int(1e5)}]
