import os
import numpy as np
params = {
  "model_type": "gdn_autoencoder",
  "model_name": "test",
  "version": "0.0",
  "num_images": 150,
  "vectorize_data": True,
  "norm_data": False,
  "center_data": True,
  "standardize_data": False,
  "contrast_normalize": False,
  "whiten_data": True,
  "whiten_method": "FT",
  "lpf_data": False,
  "lpf_cutoff": 0.7,
  "extract_patches": True,
  "num_patches": 1e6,
  "patch_edge_size": 16,
  "overlapping_patches": True,
  "randomize_patches": True,
  "patch_variance_threshold": 0.0,
  "batch_size": 200,
  "num_neurons": 768,
  "mle_step_size": 0.01,
  "num_mle_steps": 15,
  "num_triangles": 20,
  "sigmoid_beta": 1.0,
  "ramp_min": -1.0,
  "ramp_max": 1.0,
  "gdn_w_init_const": 0.1,
  "gdn_b_init_const": 0.1,
  "gdn_w_thresh_min": 1e-6,
  "gdn_b_thresh_min": 1e-6,
  "gdn_eps": 1e-6,
  "optimizer": "adam",#"annealed_sgd",
  "cp_int": 10000,
  "max_cp_to_keep": 1,
  "cp_load": False,
  "cp_load_name": "gdn_autoencoder",
  "cp_load_step": 1e4,
  "cp_load_ver": "0.0",
  "cp_load_var": ["w_enc", "b_enc", "w_dec", "b_dec", "w_gdn", "b_gdn", "w_igdn", "b_igdn"],
  "log_int": 100,
  "log_to_file": True,
  "gen_plot_int": 10000,
  "save_plots": True,
  "eps": 1e-12,
  "device": "/gpu:0",
  "rand_seed": 1234567890,
  "out_dir": os.path.expanduser("~")+"/Work/Projects/",
  "data_dir": os.path.expanduser("~")+"/Work/Datasets/"}

schedule = [
  {"weights": ["w_enc", "b_enc", "w_dec", "b_dec", "w_gdn0", "b_gdn0", "w_igdn1", "b_igdn1"],
  "ent_mult": 2.0,
  "ramp_slope": 1.0,
  "decay_mult": 0.01,
  "noise_var_mult": 0.0,
  "triangle_centers": np.linspace(-1.0, 1.0, params["num_triangles"]),
  "weight_lr": [5e-4]*8,
  "decay_steps": [int(1e5*0.8),]*8,
  "decay_rate": [0.8,]*8,
  "staircase": [True,]*8,
  "num_batches": int(1e5)}]
