import os
import numpy as np
params = {
  "model_type": "gradient_sc",
  "model_name": "gradient_sc_test",
  "version": "0.0",
  "num_images": 100,
  "vectorize_data": True,
  "norm_data": False,
  "center_data": False,
  "standardize_data": True,
  "contrast_normalize": False,
  "whiten_data": True,
  "whiten_method": "FT",
  "extract_patches": True,
  "num_patches": 1e6,
  "patch_edge_size": 8,
  "overlapping_patches": True,
  "randomize_patches": True,
  "patch_variance_threshold": 1e-6,
  "batch_size": 100,
  "num_neurons": 96,
  "num_a_steps": 40,
  "a_step_size": 0.04, # anneal the step size
  "norm_weights": True,
  "optimizer": "annealed_sgd",
  "cp_int": 10000,
  "max_cp_to_keep": 1,
  "cp_load": False,
  "cp_load_name": "pretrain_mnist",
  "cp_load_step": 150000,
  "cp_load_ver": "0.0",
  "cp_load_var": ["phi"],
  "log_int": 100,
  "log_to_file": True,
  "gen_plot_int": 100,
  "save_plots": True,
  "eps": 1e-12,
  "device": "/gpu:0",
  "rand_seed": 1234567890,
  "out_dir": os.path.expanduser("~")+"/Work/Projects/",
  "data_dir": os.path.expanduser("~")+"/Work/Datasets/"}

schedule = [
  {"weights": ["phi"],
  "sparse_mult": 0.009,
  "weight_lr": [0.09],
  "decay_steps": [int(1e6*0.25)],
  "decay_rate": [0.8],
  "staircase": [True],
  "num_batches": int(3000)}]
