import os
params = {
  "model_type": "lca_pca",
  "model_name": "lca_pca_512",
  "version": "0.0",
  "num_images": 50,
  "vectorize_images": True,
  "norm_images": False,
  "whiten_images": True,
  "contrast_normalize": False,
  "extract_patches": True,
  "num_patches": 1e3,
  "patch_edge_size": 16,
  "overlapping_patches": False,
  "randomize_patches": False,
  "patch_variance_threshold": 1e-6,
  "batch_size": 100,
  "optimizer": "annealed_sgd",
  "rectify_a": True,
  "norm_weights": True,
  "num_neurons": 512, #1024,#2560,
  "num_pooling_units": 25,
  "num_steps": 30,
  "dt": 0.001,
  "tau": 0.03,
  "thresh_type": "soft",
  "cp_int": 10000,
  "max_cp_to_keep": 1,
  "cp_load": False,
  "log_int": 100,
  "log_to_file": True,
  "gen_plot_int": 1000,
  "save_plots": True,
  "eps": 1e-12,
  "device": "/gpu:0",
  "rand_seed": 123456,
  "out_dir": os.path.expanduser("~")+"/Work/Projects/",
  "data_dir": os.path.expanduser("~")+"/Work/Datasets/"}

schedule = [
  {"weights": ["phi"],
  "sparse_mult": 0.4,
  "weight_lr": [0.10],
  "decay_steps": [int(1e4*0.8)],
  "decay_rate": [0.5],
  "staircase": [True],
  "num_batches": int(1e4)}]
