import os
params = {
  "model_type": "MLP",
  "model_name": "test",
  "out_dir": os.path.expanduser("~")+"/Work/Projects/",
  "data_dir": os.path.expanduser("~")+"/Work/Datasets/MNIST/",
  "version": "0.0",
  "optimizer": "annealed_sgd",
  "rectify_a": True,
  "norm_images": False,
  "norm_a": False,
  "norm_weights": True,
  "batch_size": 100,
  "num_pixels": 784,
  "num_classes": 10,
  "num_hidden": 400,
  "num_val": 10000,
  "num_labeled": 50000,
  "cp_int": 2000,
  "max_cp_to_keep": 5,
  "val_on_cp": True,
  "cp_load": False,
  "cp_load_name": "pretrain",
  "cp_load_val": 150000,
  "cp_load_ver": "0.0",
  "cp_load_var": ["phi"],
  "log_int": 100,
  "log_to_file": True,
  "gen_plot_int": 1000,
  "display_plots": False,
  "save_plots": True,
  "eps": 1e-12,
  "device": "/cpu:0",
  "rand_seed": 1234567890}

schedule = [
  {"weights": ["phi", "w", "bias1", "bias2"],
  "weight_lr": [0.01, 0.001, 0.01, 0.001],
  "decay_steps": [2000]*4,
  "decay_rate": [0.8]*4,
  "staircase": [True]*4,
  "num_batches": 4000}]
