import os
import numpy as np
params = {
  "model_type": "relu_autoencoder",
  "model_name": "relu_autoencoder",
  "version": "0.0",
  "num_images": 150,
  "vectorize_data": True,
  "norm_data": False,
  "center_data": False,
  "standardize_data": False,
  "contrast_normalize": False,
  "whiten_data": True,
  "whiten_method": "FT",
  "lpf_data": False,
  "lpf_cutoff": 0.7,
  "extract_patches": True,
  "num_patches": 1e6,
  "patch_edge_size": 9,#16,
  "overlapping_patches": True,
  "randomize_patches": True,
  "patch_variance_threshold": 0.0,
  "batch_size": 300,
  "num_neurons": 81,#256,
  "mle_step_size": 0.01,
  "num_mle_steps": 15,
  "num_triangles": 20,
  "sigmoid_beta": 2.0,
  "optimizer": "adam",#"annealed_sgd",
  "cp_int": 50000,
  "max_cp_to_keep": 1,
  "cp_load": False,
  "cp_load_name": "relu_autoencoder",
  "cp_load_step": 1e4,
  "cp_load_ver": "0.0",
  "cp_load_var": ["w_enc", "b_enc", "w_dec", "b_dec"],
  "log_int": 10,
  "log_to_file": True,
  "gen_plot_int": 500,
  "save_plots": True,
  "eps": 1e-12,
  "device": "/gpu:0",
  "rand_seed": 1234567890,
  "out_dir": os.path.expanduser("~")+"/Work/Projects/",
  "data_dir": os.path.expanduser("~")+"/Work/Datasets/"}

schedule = [
  {"weights": ["w_enc", "b_enc", "w_dec", "b_dec"],
  "ent_mult": 0.20,
  "decay_mult": 0.01,
  "noise_var_mult": 0.05,
  "triangle_centers": np.linspace(-1.0, 1.0, params["num_triangles"]),
  "weight_lr": [0.01,]*4,
  "decay_steps": [int(1e5*0.8),]*4,
  "decay_rate": [0.5,]*4,
  "staircase": [True,]*4,
  "num_batches": int(1e5)}]
