import os
params = {
  "model_type": "sigmoid_autoencoder",
  "model_name": "sigmoid_autoencoder",
  "version": "0.0",
  "num_images": 150,
  "vectorize_data": True,
  "norm_data": False,
  "center_data": False,
  "standardize_data": True,
  "contrast_normalize": False,
  "whiten_data": True,
  "whiten_method": "FT",
  "lpf_data": False,
  "lpf_cutoff": 0.7,
  "extract_patches": True,
  "num_patches": 1e6,
  "patch_edge_size": 16,
  "overlapping_patches": True,
  "randomize_patches": True,
  "patch_variance_threshold": 0.0,
  "batch_size": 100,
  "num_neurons": 768,
  "optimizer": "adam",#"annealed_sgd",
  "cp_int": 10000,
  "max_cp_to_keep": 1,
  "cp_load": False,
  "log_int": 100,
  "log_to_file": True,
  "gen_plot_int": 1000,
  "save_plots": True,
  "eps": 1e-12,
  "device": "/gpu:0",
  "rand_seed": 123456789,
  "out_dir": os.path.expanduser("~")+"/Work/Projects/",
  "data_dir": os.path.expanduser("~")+"/Work/Datasets/"}

schedule = [
  {"weights": ["w_enc", "b_enc", "w_dec", "b_dec"],
  "sparse_mult": 4.0,
  "decay_mult": 0.02,
  "target_act": 0.01,
  "weight_lr": [0.01,]*4,
  "decay_steps": [int(1e4*0.5),]*4,
  "decay_rate": [0.5,]*4,
  "staircase": [True,]*4,
  "num_batches": int(1e4)}]
