import os
params = {
  "model_type": "sigmoid_autoencoder",
  "model_name": "sigmoid_autoencoder_mnist",
  "version": "0.0",
  #"num_images": 150,
  "vectorize_data": True,
  "norm_data": False,
  "rescale_data": True,
  "center_data": False,
  "standardize_data": False,
  "contrast_normalize": False,
  "whiten_data": False,#True,
  #"whiten_method": "FT",
  "lpf_data": False,
  "lpf_cutoff": 0.7,
  "extract_patches": False,#True,
  #"num_patches": 1e6,
  #"patch_edge_size": 16,
  #"overlapping_patches": True,
  #"randomize_patches": True,
  #"patch_variance_threshold": 0.0,
  "batch_size": 200,
  "num_neurons": 768,
  "optimizer": "annealed_sgd",#"adam",
  "cp_int": 100000,
  "max_cp_to_keep": 1,
  "cp_load": False,
  "log_int": 100,
  "log_to_file": True,
  "gen_plot_int": 100000,
  "save_plots": True,
  "eps": 1e-12,
  "device": "/gpu:0",
  "rand_seed": 123456789,
  "out_dir": os.path.expanduser("~")+"/Work/Projects/",
  "data_dir": os.path.expanduser("~")+"/Work/Datasets/"}

schedule = [
  {"weights": ["w_enc", "b_enc", "w_dec", "b_dec"],
  "decay_mult": 0.005,
  "sparse_mult": 0.01, # How important is the sparse loss (tradeoff parameter)
  "target_act": 0.09, # Target firing rate for neurons
  "weight_lr": [0.01,]*4,
  "decay_steps": [int(3e6*0.4),]*4,
  "decay_rate": [0.5,]*4,
  "staircase": [True,]*4,
  "num_batches": int(3e6)}]
