import os
params = {
  "model_type": "vae",
  "model_name": "vae_mnist",
  "version": "0.0",
  "vectorize_data": True,
  "norm_data": False,
  "rescale_data": True,
  "center_data": False,
  "standardize_data": False,
  "contrast_normalize": False,
  "whiten_data": False,
  "lpf_data": False,
  "lpf_cutoff": 0.7,
  "extract_patches": False,
  "batch_size": 200,
  "num_neurons": 256,
  "optimizer": "annealed_sgd",#"adam",
  "cp_int": 100000,
  "max_cp_to_keep": 1,
  "cp_load": False,
  "log_int": 100,
  "log_to_file": True,
  "gen_plot_int": 100000,
  "save_plots": True,
  "eps": 1e-6,
  "device": "/gpu:0",
  "rand_seed": 123456789,
  "out_dir": os.path.expanduser("~")+"/mountData/",
  "data_dir": os.path.expanduser("~")+"/mountData/dataset/",
  }

schedule = [
  {"weights": ["w_enc_mean", "b_enc_mean", "w_enc_std", "b_enc_std", "w_dec", "b_dec"],
  "decay_mult": 0.0,
  "weight_lr": [0.001,]*6,
  "decay_steps": [int(3e6*0.4),]*6,
  "decay_rate": [0.5,]*6,
  "staircase": [True,]*6,
  "num_batches": int(3e6)}]
