import os

params = {
  "model_type": "karklin_lewicki",
  "model_name": "test",
  "output_dir": os.path.expanduser("~")+"/Work/Projects/",
  "data_dir": os.path.expanduser("~")+"/Work/Datasets/MNIST/",
  "version": "0.0",
  "optimizer": "annealed_sgd",
  "rectify_u": False,
  "rectify_v": False,
  "norm_images": False,
  "norm_a": False,
  "norm_weights": True,
  "batch_size": 500,
  "num_pixels": 784,
  "num_u": 400,
  "num_v": 10,
  "num_steps": 20,
  "cp_int": 15000,
  "max_cp_to_keep": 5,
  "cp_load": False,
  "cp_load_name": "pretrain",
  "cp_load_val": 150000,
  "cp_load_ver": "0.0",
  "cp_load_var": ["a"],
  "log_int": 10,
  "log_to_file": True,
  "gen_plot_int": 10,
  "display_plots": False,
  "save_plots": True,
  "eps": 1e-12,
  "device": "/cpu:0",
  "rand_seed": 1234567890}

schedule = [
  #{"weights": ["a"],
  #"recon_mult": 1.0,
  #"sparse_mult": 1.0,
  #"u_step_size": 0.1,
  #"v_step_size":0.0,
  #"weight_lr": [0.1],
  #"decay_steps": [30000],
  #"decay_rate": [0.8],
  #"staircase": [True],
  #"num_batches": 1000}]#,

  {"weights": ["a", "b"],
  "recon_mult": 1.0,
  "sparse_mult": 1.0,
  "u_step_size": 0.05,
  "v_step_size": 0.002,
  "weight_lr": [0.05, 0.005],
  "decay_steps": [30000]*2,
  "decay_rate": [0.8]*2,
  "staircase": [True]*2,
  "num_batches": 5000}]
